version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    container_name: genetic-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "genetic123"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  genetic-processor:
    build: .
    container_name: genetic-processor-api
    ports:
      - "8000:8000"
    environment:
      CLICKHOUSE_URL: "jdbc:clickhouse://clickhouse:8123/default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "genetic123"
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pde_api.rule=Host(`example.dahiwas.com`)"
      - "traefik.http.routers.pde_api.entrypoints=websecure"
      - "traefik.http.services.pde_api.loadbalancer.server.port=8000"
      - "traefik.http.routers.pde_api.tls.certresolver=leresolver"
      - "traefik.http.routers.pde_api.service=pde_api"
      - "traefik.docker.network=traefik"

volumes:
  clickhouse-data:

networks:
  traefik:
    external: true 
